services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  # Doporučuji přesunout Dockerfile do rootu
    container_name: skywitness-app
    ports:
      - "8000:80"
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/src
      - ./templates:/var/www/templates
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_NAME=skywitness
      - DB_USER=postgres
      - DB_PASSWORD=postgres

  db:
    image: postgres:13-alpine
    container_name: skywitness-db
    environment:
      - POSTGRES_DB=skywitness
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/data:/docker-entrypoint-initdb.d/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d skywitness"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: